# Generated by Django 2.0 on 2019-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181229_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tester'), (2, 'Company')], null=True, verbose_name='user type'),
        ),
    ]
