# Generated by Django 2.0 on 2019-01-24 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('date_start', models.DateTimeField(verbose_name='start date')),
                ('date_end', models.DateTimeField(verbose_name='end date')),
                ('number', models.PositiveSmallIntegerField(verbose_name='amount to pay')),
                ('slug', models.SlugField(max_length=151, verbose_name='slug')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_create', to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts_areas.PostArea', verbose_name='post category')),
                ('post_subcategory', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts_areas.PostArea', verbose_name='post sub category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='ActiveJob',
            fields=[
            ],
            options={
                'verbose_name': 'active job',
                'verbose_name_plural': 'active jobs',
                'proxy': True,
                'indexes': [],
            },
            bases=('posts.job',),
        ),
    ]
