# Generated by Django 2.0 on 2019-01-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, default='asd', max_length=128, verbose_name='name'),
            preserve_default=False,
        ),
    ]
